dist: xenial
language: node_js
before_install:
  - $TRAVIS_BUILD_DIR/.travis/install_system_audio.sh
  - sudo bash $TRAVIS_BUILD_DIR/.travis/prep-dummy-soundcard.sh
  - jackd --help
  - $TRAVIS_BUILD_DIR/.travis/install_supercollider.sh
  - $TRAVIS_BUILD_DIR/.travis/install_supercolliderjs_config.sh
  - $TRAVIS_BUILD_DIR/.travis/install_quark.sh
cache:
  directories:
    - $HOME/supercollider
    - $HOME/sc3-plugins
env:
  global:
    AUDIODEV=null
